### ISSUE TITLE
Audio/Video feeds not coming through

### ISSUE THREAD

**Issue by AidanNelson** [AidanNelson/YORB2020#35]
As of today, many A/V feeds are not coming through or are only coming through in one direction.  What is up with that?

**Comment by miamiww** [comment]
I tested with a friend after the show and our feeds came through, there were only a few people in there.

Here are some possibilities that come to my mind:
* qVGA request is unsupported for some browsers/ webcams and rather than being ignored is preventing getUserMedia => fix is either to remove or to check getSupportedConstraints() to make sure height and width are support (however all modern browsers support height and width constraints, issue might be the way the browser is speaking to the webcam, which wouldn't be visible from the POV of the website; moreover `ideal` is ignored by anything that can't support it according to "the manual")
* ¯\_(ツ)_/¯ lots o people - video and audio feeds seemed to crash when testing with lots of people before, could have crashed early, causing most users to see black cubes and assume that the norm was camera and mic muted rather than thinking they needed to refresh

**Comment by AidanNelson** [comment]
Hey -- I think this was a bug with the polling and update logic.  I've cleaned it up a bit and think it is fixed by #36.  Your second point is right, though!  There needs to be a better way to encourage open cameras!
